### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by matheusalbino** [dschwen/switch-header-source#30] opened 2018-04-03 14:23 UTC
Mac OS High Sierra 10.13.4
Atom 1.25.0 x64
switch-header-source 0.28.0

Steps:
1. Save file (auto format on save with atom-beautify)

The file: '/Users/(name)/(project)/src/private/net/network.cpp'

```
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/(name)/(project)/src/private/net/.atom-beautify.network.cpp'
```
```
fs.js:961

Error: ENOENT: no such file or directory, lstat '/Users/(name)/(project)/src/private/net/.atom-beautify.network.cpp'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1641:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at Object.switchMapAdd (/Users/(name)/.atom/packages/switch-header-source/lib/switch-header-source.coffee:71:21)
    at /Users/(name)/.atom/packages/switch-header-source/lib/switch-header-source.coffee:116:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at didChangeCallback (/Applications/Atom.app/Contents/Resources/app/src/project.js:357:28)
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:539:13)
    at sub.native.onDidChange.events (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:464:64)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:325:24)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:133:13)
```

**Comment by dschwen** [comment] 2018-04-03 14:45
Duplicate of #29 
I'm closing this and will tag you on the other issue.

**Closed by dschwen** 2018-04-03 14:45 UTC
